osx_image: xcode8
language: objective-c
rvm: 2.2.2
cache: cocoapods

env:
  global:
    - PROJECT=EZSwiftExtensions.xcodeproj

before_install:
  - gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty
  - brew install swiftlint

before_script:
  - swiftlint
  - bundle exec danger --fail-on-errors=true

script:
  - set -o pipefail
  
  - xcodebuild clean build test -project "$PROJECT" -scheme EZSwiftExtensions-iOS -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' | XCPRETTY_JSON_FILE_OUTPUT="xcodebuild.json" xcpretty -f `xcpretty-json-formatter`
  - xcodebuild clean build test -project "$PROJECT" -scheme EZSwiftExtensions-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0' | xcpretty

  - pod _1.1.0.rc2_ lib lint

after_success:
  - bash <(curl -s https://codecov.io/bash)
